### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by sscarduzio** [martende/gemini#2]
Not sure if it's  because I'm using a more recent phantomjs binary, but this:

``` scala
import akka.gemini.PhantomExecutor
import akka.actor.ActorSystem
import scala.concurrent.duration._

object Hi extends App {
    implicit val system = ActorSystem("MySystem")
    PhantomExecutor.initEnvironment

    val p = PhantomExecutor(isDebug=true)


    scala.concurrent.Await.result({
      p.open("https://www.google.com")
    },10 seconds)

    p.render("screen.png")
    p.close()

    println("Screenshot screen.png done.")
    system.shutdown()

}
```

Using this

``` hocon
phantom {
  // Path to binary phantomjs file - this repo produces 64bit compiled for ubuntu jessie bin
  // bin/phantomjs: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, BuildID[sha1]=6d1ee78f9e4370d6a33ebcb2cf989be26d4961e5, not stripped

  bin = "/usr/local/bin/phantomjs"
  // Some Extra args for phantomjs
  //args  =["--proxy=127.0.0.1:3128"]
  args = []
}
```

throws this:

```
[INFO] [09/13/2016 16:40:50.878] [MySystem-akka.actor.default-dispatcher-2] [akka://MySystem/user/PhantomExecutor-1] OpenUrl 'https://www.google.com'
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
    at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
    at scala.concurrent.Await$.result(package.scala:190)
    at Hi$.delayedEndpoint$Hi$1(Main.scala:15)
    at Hi$delayedInit$body.apply(Main.scala:8)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at Hi$.main(Main.scala:8)
    at Hi.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

What version of phantomjs did you test this with?

**Comment by martende** [comment]
Hi thank you for your fix.

From install docs:

Gemini uses pathched version of phantomjs with asyncIo api from https://github.com/execjosh/phantomjs.git and branch WIP-async-file-io or https://github.com/martende/phantomjs/tree/ASYNC_1.9 patched 1.9 version. Warning !!! - On current 1.9 phantomjs release gemini does not work.

The reason is standart phantom does not support async stdin/stdoud reading. This patch allowes it.

**Comment by sscarduzio** [comment]
Oh ok, didn't see that. Will the async patch ever be merged in the official phantomjs? Otherwise we're stuck with an old phantomjs version.

**Comment by martende** [comment]
As I know there is no async IO in phantom v. 2 also . 
I have manually patched it the similar way. 
But what is actual status of phantom I don't  now. 

I am thinking about overwiting core using webdriver socker . But it looses some nice functionality like event notifying from phantom.
